#!/bin/bash
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/article_categories_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/article_categories_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/article_templates_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/category_labels_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/category_labels_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/disambiguations_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/disambiguations_en_uris_unredirected_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/disambiguations_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/disambiguations_unredirected_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/external_links_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/external_links_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/freebase_links_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/geo_coordinates_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/geo_coordinates_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/homepages_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/homepages_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/images_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/images_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/infobox_properties_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/infobox_properties_en_uris_unredirected_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/infobox_properties_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/infobox_properties_unredirected_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/infobox_property_definitions_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/infobox_property_definitions_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/infobox_test_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/instance_types_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/instance_types_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/interlanguage_links_chapters_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/interlanguage_links_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/iri_same_as_uri_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/labels_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/labels_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/long_abstracts_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/long_abstracts_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/mappingbased_properties_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/mappingbased_properties_en_uris_unredirected_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/mappingbased_properties_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/mappingbased_properties_unredirected_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/old_interlanguage_links_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/out_degree_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/page_ids_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/page_length_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/page_links_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/page_links_en_uris_unredirected_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/page_links_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/page_links_unredirected_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/redirects_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/redirects_transitive_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/revision_ids_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/revision_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/short_abstracts_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/short_abstracts_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/skos_categories_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/skos_categories_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/specific_mappingbased_properties_en_uris_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/specific_mappingbased_properties_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/topical_concepts_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/topical_concepts_unredirected_pt.nt.bz2
wget http://data.dws.informatik.uni-mannheim.de/dbpedia/2014/pt/wikipedia_links_pt.nt.bz2
